### PR TITLE
edit/create chore, avatars left, css,

### PR DESCRIPTION
**Pull request by GrodanBool**
user can now edit/create chores in relevant menus, centered avatars left in choredetailscreen.tsx and made some css changes

### CODE REVIEW

**Comment by EmelieBrobergs** [comment]
The black shadow don't cover the bottom, may due to css "position: "absolute" that I used in the Screen behind ?
image
image

The buttons are black in my emulator, may due to warning of version of React native paper?
image

Suggestion, I think It would look better if the score circles were spaced evenly, not placed at the left.
image

**Review by Erik-wiklund — DISMISSED** [review]

**Comment by EmelieBrobergs** [comment]
image
This looks really good!

image
Tries to edit css in screen behind, but that dont seems to be the problem with the background don't cover the bottom.  If this problem doesn't occur in our phones we don't need to fix it, but please check.

**Comment by EmelieBrobergs** [comment]
On my phone

**Review by EmelieBrobergs — APPROVED** [review]
Created new issue for the noted problem, issue #100

**Comment by ViktorNy** [comment]
> 
> 
> Created new issue for the noted problem, issue #100

Same problem for as well

**Review by Erik-wiklund — APPROVED** [review]

**Review by 87rasnyg — APPROVED** [review]

**Review by ViktorNy — APPROVED** [review]
Tried this out and helped with other devices so it works now. Approved.

**Pull request merged**
